# PlatformIO pre-script: bake the BLE pairing passkey into the firmware.
#
# - BLE_PASSKEY env var set    -> use it (re-flash a device keeping its code)
# - uploading, no env var      -> generate a new random 6-digit passkey
# - plain build, no env var    -> keep the previous one (or generate if none)
#
# The passkey is written to <build dir>/ble_passkey/ble_passkey.h (picked up by Conf.cpp via
# __has_include), printed at the start and at the end of the upload, and appended to
# ble_passkeys.log (git-ignored).
import os
import secrets
from datetime import datetime

Import("env")

gen_dir = os.path.join(env.subst("$BUILD_DIR"), "ble_passkey")
header = os.path.join(gen_dir, "ble_passkey.h")
uploading = "upload" in COMMAND_LINE_TARGETS


def read_previous():
    try:
        with open(header) as f:
            return int(f.read().split("BLE_PASSKEY")[1].split()[0])
    except (OSError, IndexError, ValueError):
        return None


def pick_passkey():
    requested = os.environ.get("BLE_PASSKEY")
    if requested:
        if not (requested.isdigit() and len(requested) == 6 and requested[0] != "0"):
            env.Exit("BLE_PASSKEY must be 6 digits and not start with 0")
        return int(requested)
    previous = read_previous()
    if previous is not None and not uploading:
        return previous
    return 100000 + secrets.randbelow(900000)  # 100000..999999


def banner(passkey):
    line = "=" * 46
    print("\n%s\n  BLE PAIRING PASSKEY [%s]:  %06d\n%s\n" % (line, env["PIOENV"], passkey, line))


passkey = pick_passkey()
os.makedirs(gen_dir, exist_ok=True)
with open(header, "w") as f:
    f.write("// generated by tools/ble_passkey.py - do not edit\n#define BLE_PASSKEY %d\n" % passkey)
env.Append(CPPPATH=[gen_dir])

banner(passkey)
if uploading:
    with open(os.path.join(env.subst("$PROJECT_DIR"), "ble_passkeys.log"), "a") as log:
        log.write("%s  %s  %06d\n" % (datetime.now().isoformat(timespec="seconds"), env["PIOENV"], passkey))
    env.AddPostAction("upload", lambda *args, **kwargs: banner(passkey))
